FROM node:18.7.0

RUN mkdir -p /app
WORKDIR /app

COPY tsconfig.json .

RUN npm install -g typescript

COPY package.json .
RUN npm install

RUN npm run build

COPY dist /app/dist

CMD ["node", "dist/server.js"]