name: Deploy Prod to DonWeb

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: prod

    env:
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      APIV1: ${{ secrets.APIV1 }}
      APIV2: ${{ secrets.APIV2 }}
      PORT: ${{ secrets.PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove existing container
        run: docker rm -f api-print-poscloud || true

      - name: Build Docker image
        run: docker build -t api-print-poscloud -f Dockerfile.prod .

      - name: Run Docker container
        run: |
          docker run \
            -e TOKEN_SECRET=$TOKEN_SECRET \
            -e APIV1=$APIV1 \
            -e APIV2=$APIV2 \
            -e PORT=$PORT \
            -v /home:/home \
            --restart unless-stopped \
            --net host \
            --name api-print-poscloud \
            -d -it -p 302:302 api-print-poscloud
